### ISSUE TITLE
MultipartEncodedDataProcessor shouldn't read all bytes into memory

### ISSUE THREAD

**Issue by wanghongfei** [OpenFeign/feign-form#2]
I quickly browsed source code of the `MultipartEncodedDataProcessor` class of the project. I found that it reads all bytes to memory then write them to request body once. This isn't the best way to use `multipart/form-data`. It should read one block of bytes  and send it to server one by one.

copied from [open-feign](https://github.com/OpenFeign/feign/issues/455)

**Comment by xxlabaza** [comment]
Yes, you are right, I will take a look on it ASAP

**Comment by SoulSong** [comment]
When I use ‘feign-form-spring’ and 'feign-form' in my springcloud project.I found that I could not use@Requestboby annotation for Map,User  like below:
`public String postBobyAParamAPathVar(
    		@RequestBody(required=true) Map<String, Object> map,
    		@RequestParam(value="userName") String userName,
    		@PathVariable(value="id") String id){
.......
}`

**Comment by xxlabaza** [comment]
So, this is a limitation of Feign library. Close issue
