### ISSUE TITLE
v2.2.0 not deployed to mvn central

### ISSUE THREAD

**Issue by maaydin** [OpenFeign/feign-form#21]
While v2.2.0 exists on bintray repo, not deployed to mvn central. There must be some problem with deploying to mvn central.

http://dl.bintray.com/openfeign/maven/io/github/openfeign/form/feign-form/
https://repo.maven.apache.org/maven2/io/github/openfeign/form/feign-form/

**Comment by xxlabaza** [comment]
Thanks a lot!
I have triggered manually sync in bintray (it seems something was wrong with this service), after few hours it should be synced
