### ISSUE TITLE
lombok dependency scope provided

### ISSUE THREAD

**Issue by mohic** [OpenFeign/feign-form#22]
Hi,

Thanks for this library.

I noticed that your project depend on Lombok but you specify that it's required on compile time.

It is probably not necessary and provided scope can be apply (see https://projectlombok.org/setup/maven)

Best regards,
Christophe

**Comment by xxlabaza** [comment]
Thanks a lot! I have published a new `2.2.1` version with your update

**Comment by hellboy81** [comment]
why `provided`?

**Comment by mohic** [comment]
@hellboy81 ,

The goal of Lombok is to automatically generate getter, setter and other boring things. Thus, it is used only for compiling feign-form library, not for use it
