### ISSUE TITLE
Byte array parameter leads to octet-stream Content-Type and `"null"` file name

### ISSUE THREAD

**Issue by GuiSim** [OpenFeign/feign-form#23]
From MultipartEncodedDataProcessor.java

```
    protected void writeByteOrFile (OutputStream output, PrintWriter writer, String name, Object value) {
        if (value instanceof byte[]) {
            writeByteArray(output, writer, name, null, null, (byte[]) value);
        } else {
            writeFile(output, writer, name, null, (File) value);
        }
    }
```

You can see that `writeByteArray` always receives null as the originalFileName and null as the contentType.

I wish there was a way to tell the library which content-type and which file name to use without resorting to saving a temporary file to disk.

Perhaps there should be a way to configure the library so that it can detect file headers? 
In my case, I will always be sending the same file type so even a static solution would be acceptable. 

Thanks

**Comment by xxlabaza** [comment]
From newer version 3.0.1, you are able to override FormEncoder behaviour:

Your case (with static originalFileName):

https://github.com/OpenFeign/feign-form/blob/3.0.1/feign-form/src/test/java/feign/form/CustomClientTest.java
