### ISSUE TITLE
File upload with json data not working

### ISSUE THREAD

**Issue by kittugit** [OpenFeign/feign-form#24]
I try to submit both file and data as follows.. Getting "Unsupported Media Type"
`@RequestLine("POST /upload")
@Headers("Content-Type: multipart/form-data")
Foo uploadFile(@Param("foo")Foo foo, @Param("file") File file);`

Spring Service which i try to consume
` @RequestMapping(value = "/upload", method = RequestMethod.POST, consumes = { MediaType.MULTIPART_FORM_DATA_VALUE})
    public ResponseEntity<Foo> handleFileUpload(@RequestPart("foo") Foo foo, @RequestPart("file") MultipartFile file) {`

**Comment by gsbtech** [comment]
I have the same problem.  Have you found any solution?

**Comment by xxlabaza** [comment]
Try the newer feign-form version: 3.0.0

This code works:

Feign client:

```java
  @RequestLine("POST /upload/with_json")
  @Headers("Content-Type: multipart/form-data")
  Response uploadWithJson (@Param("dto") Dto dto, @Param("file") File file);
```

Spring controller:

```java
  @PostMapping(
      path = "/upload/with_json",
      consumes = MULTIPART_FORM_DATA_VALUE
  )
  public ResponseEntity<Long> uploadWithJson (@RequestPart("dto") String dtoString,
                                              @RequestPart("file") MultipartFile file
  ) throws IOException {
    val dto = objectMapper.readValue(dtoString, Dto.class);
    val status = dto != null && dto.getName().equals("Artem")
           ? OK
           : I_AM_A_TEAPOT;
    return ResponseEntity.status(status).body(file.getSize());
  }
```
