### ISSUE TITLE
Multiple File Upload

### ISSUE THREAD

**Issue by kittugit** [OpenFeign/feign-form#25]
File array is not working properly..  array is received as empty in the server side

Client Code
`@RequestLine("POST /upload")
	    @Headers("Content-Type: multipart/form-data")
	    Foo uploadFile(@Param("file") File files[]);`

Spring Service

` @RequestMapping(value = "/upload", method = RequestMethod.POST, consumes = { MediaType.MULTIPART_FORM_DATA_VALUE})
    public ResponseEntity<Foo> handleFileUpload(@RequestPart("file") MultipartFile file[]) {`

**Comment by xxlabaza** [comment]
Try the newer version 3.0.0

This code works:

Feign client (if you use SpringFormEncoder, you also could use MultipartFile instead of File):

```java
  @RequestLine("POST /upload/files")
  @Headers("Content-Type: multipart/form-data")
  String uploadWithArray (@Param("files") File[] files);

  @RequestLine("POST /upload/files")
  @Headers("Content-Type: multipart/form-data")
  String uploadWithList (@Param("files") List<File> files);
```

Server code:

```java
  @RequestMapping(value = "/upload/files", method = POST)
  public ResponseEntity<Long> upload (@RequestParam("files") MultipartFile[] files) {
    HttpStatus status;
    if (files[0].getSize() == 0 || files[1].getSize() == 0) {
      status = I_AM_A_TEAPOT;
    } else if (files[0].getOriginalFilename() == null || files[0].getOriginalFilename().trim().isEmpty() ||
               files[1].getOriginalFilename() == null || files[1].getOriginalFilename().trim().isEmpty()) {
      status = CONFLICT;
    } else {
      status = OK;
    }
    return ResponseEntity.status(status).body(files[0].getSize() + files[1].getSize());
  }
```
