### ISSUE TITLE
Example in readme breaks non feign-form clients

### ISSUE THREAD

**Issue by psxpaul** [OpenFeign/feign-form#26]
The example in the readme to include:

> @Configuration
> public class MultipartSupportConfig {
> ...
> }

Breaks other feign clients that do need feign-form. The relevant part of the stacktrace is:
> feign.codec.EncodeException: class com.concur.ais.cloudelements.model.ElementInstance is not a type supported by this encoder.
> 	at feign.codec.Encoder$Default.encode(Encoder.java:90)
> 	at feign.form.spring.SpringFormEncoder.encode(SpringFormEncoder.java:35)
> 	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:351)
> 	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:213)
> 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
> 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
> 	at com.sun.proxy.$Proxy125.createInstance(Unknown Source)

The Spring documentation [here](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html#spring-cloud-feign-overriding-defaults) indicates that the @Configuration annotation is not needed, and actually harmful if the class is included in ComponentScanning:

> FooConfiguration does not need to be annotated with @Configuration. However, if it is, then take care to exclude it from any @ComponentScan that would otherwise include this configuration as it will become the default source for feign.Decoder, feign.Encoder, feign.Contract, etc., when specified. This can be avoided by putting it in a separate, non-overlapping package from any @ComponentScan or @SpringBootApplication, or it can be explicitly excluded in @ComponentScan.

**Comment by xxlabaza** [comment]
Thanks a lot for your comment, I will fix readme asap

**Comment by xxlabaza** [comment]
done
