### ISSUE TITLE
Multipart Object contenttype defaulting to text/plain

### ISSUE THREAD

**Issue by AkashMegaravalli** [OpenFeign/feign-form#29]
I had a scenario where multipart was supposed to be json which goes as object and a image file, But json object passed was having content type as "text/plain" ,Because that was hardcoded in ParamWriter.java.  So i modified that code to let Impl user mention what type of content type he os passing.  I modified that part and checked into my repo, 

https://github.com/AkashMegaravalli/feign-form-content-type

**Comment by xxlabaza** [comment]
You could use Guillaume Simard's code from [his PR](https://github.com/OpenFeign/feign-form/pull/38)

It was already published as Feign-Form version 3.3.0
