### ISSUE TITLE
Extract support for MultipartFile to separate module

### ISSUE THREAD

**Issue by tjuchniewicz** [OpenFeign/feign-form#3]
Now by default feign-form includes:

```xml
<dependency>
   <groupId>org.springframework</groupId>
   <artifactId>spring-web</artifactId> 
   <scope>compile</scope>
</dependency>
```

it can be problematic in some cases so support for `MultipartFile`  from Spring should be moved to separate module.

See discussion: #1

**Comment by xxlabaza** [comment]
It is interesting, I am going to take a look at this problem this weekend, thanks
