### ISSUE TITLE
Multipart request body is not present in 3.0.1+, but present in 2.2.1

### ISSUE THREAD

**Issue by solomkinmv** [OpenFeign/feign-form#34]
Here is part of my feign client:

```
@FeignClient(
        name = "storage-service",
        path = "/storage-service",
        configuration = StorageClient.MultipartSupportConfig.class
)
public interface StorageClient {

    String UPLOAD_IMG_KEY = "file";

    @PostMapping("/")
    ResponseEntity<Void> save(@RequestParam("type") StoredType type,
                              @RequestPart(UPLOAD_IMG_KEY) MultipartFile file);

    class MultipartSupportConfig {

        @Autowired
        private ObjectFactory<HttpMessageConverters> messageConverters;

        @Bean
        public Encoder feignFormEncoder() {
            return new SpringFormEncoder(new SpringEncoder(messageConverters));
        }
    }
}
```

And here is test using wiremock:

    @Test
    public void savesMultipartFile() {
        String imagePngContentType = "image/png";
        String fileContent = "nonsensecontent";
        String location = "location";
        stubFor(any(urlPathMatching("/storage-service/\\\\?.*"))
                        .withQueryParam("type", equalTo("IMG"))
                        .withMultipartRequestBody(
                                aMultipart()
                                        .withName("file")
                                        .withHeader("Content-Type", containing(imagePngContentType))
                                        .withBody(binaryEqualTo(fileContent.getBytes())))
                        .willReturn(aResponse()
                                            .withStatus(OK_200)
                                            .withHeader("Location", location)));
        MockMultipartFile file = new MockMultipartFile("file", "image.png", imagePngContentType,
                                                       fileContent.getBytes());

        ResponseEntity<Void> response = storageClient.save(StoredType.IMG, file);

        assertThat(response.getStatusCode().value()).isEqualTo(OK_200);
        assertThat(response.getHeaders().get("Location")).containsOnly(location);
    }

I use following dependencies:

	compile 'io.github.openfeign.form:feign-form:3.2.2'
	compile 'io.github.openfeign.form:feign-form-spring:3.2.2'

With version `3.0.1+` I receive following error from wiremock:

```
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
ANY                                                        | POST
/storage-service/\\?.*                                     | /storage-service/?type=IMG
                                                           |
Query: type = IMG                                          | type: IMG
                                                           |
[Multipart request body]                                   |                                                     <<<<< [Multipart request body] is not present
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

But with version `2.2.1` everything is OK.

Who can explain this behavior?

**Comment by xxlabaza** [comment]
@solomkinmv, I have reproduced your problem and investigated it, please take a look at this [branch](https://github.com/OpenFeign/feign-form/blob/issue34/feign-form-spring/src/test/java/feign/form/feign/spring/issue34/WireMockTest.java)

So, first, you didn't specify content-type request header, like [this](https://github.com/OpenFeign/feign-form/blob/issue34/feign-form-spring/src/test/java/feign/form/feign/spring/issue34/StorageClient.java#L47)

Second, it seems it was a bug in versions under 3 with content-type recognition, so that's why it was ok for you
