### ISSUE TITLE
Content-Type for java.io.File Parameters can be null

### ISSUE THREAD

**Issue by Laures** [OpenFeign/feign-form#39]
The `AbstractWriter` uses `URLConnection.guessContentTypeFromName` to detect the file content type. This method returns null for unknown file-endings (like .m3u), which results in a Multipart Part with `Content-Type: null` and not the normal fallback of `application/octet-stream`

**Comment by xxlabaza** [comment]
What version do you use?
As I can see in the last version, [here](https://github.com/OpenFeign/feign-form/blob/master/feign-form/src/main/java/feign/form/multipart/AbstractWriter.java#L72), you are wrong.

**Comment by Laures** [comment]
I'm using 3.2.2 from maven central. if this is already fixed, please release soon.

**Comment by xxlabaza** [comment]
As you can see in URL above, it is already in version 3.2.2...

**Comment by Laures** [comment]
I'm wrong, sorry. there is a **3.3.0** release that my maven can't find for some reason. (and the commit is not in **3.2.2** according to your release tag, my link above)

I'm not sure why my maven and build server refuse to see the 3.3.0 release that is on maven central, but at least i know its there now.
