### ISSUE TITLE
How read multipart/form-data (json + octet stream)

### ISSUE THREAD

**Issue by chsi13** [OpenFeign/feign-form#45]
How is it possible to read form-data with a boundary containing octet-stream type (the file) and a boundary containing application/json (metadata) ??

FormHttpMessageConverter is encode-only ... how can I decode this response ??

Thx

**Comment by xxlabaza** [comment]
You can do it like in [this test](https://github.com/OpenFeign/feign-form/blob/master/feign-form/src/test/java/feign/form/BasicClientTest.java#L143), its server side is [here](https://github.com/OpenFeign/feign-form/blob/master/feign-form/src/test/java/feign/form/Server.java#L150).
