### ISSUE TITLE
A way to avoid OutOfMemoryError sending large files?

### ISSUE THREAD

**Issue by tworogue** [OpenFeign/feign-form#46]
Is there any way to send multipart file using feign-form without clashing with OutOfMemory error (if file is big enough and memory pool is low enough)?

Some tricky encoder to use?

**Comment by xxlabaza** [comment]
Unfortunately no. It is Feign's "feature". We have [RequestTemplate](https://github.com/OpenFeign/feign/blob/989fbd7c1f4029c6ad5900f0c3e591323cc11ffc/core/src/main/java/feign/RequestTemplate.java) and we should [set the body's byte array into it](https://github.com/OpenFeign/feign/blob/989fbd7c1f4029c6ad5900f0c3e591323cc11ffc/core/src/main/java/feign/RequestTemplate.java#L721).
