### ISSUE TITLE
Getting NULL object for request containing two form param (object and file stream)

### ISSUE THREAD

**Issue by rinkymangal2010** [OpenFeign/feign-form#49]
Getting null at server side when I am sending a HTTP 'post' request with two form parameters(An Object and file stream ).

My client code looks like:
    @POST
    @Path("/url")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public Response upload(
    		@FormParam("obj") final Obj obj,
    		@FormParam("stream") final InputStream stream)
            throws Exception;

I have done following steps:
1.  Added dependency for 'feign-form':
     compile group: 'io.github.openfeign.form', name: 'feign-form', version: '3.0.0'
2. Added file encoder
3. Updated the contract to JAXRSContract.

I have added logger to print the form param at server and getting:
obj -> null, 
file -> org.jvnet.mimepull.DataHead$ReadMultiStream@61716290

**Comment by xxlabaza** [comment]
Sorry, but FeignForm doesn't work with **InputStream**s and doesn't support it in Feign's interfaces
