### ISSUE TITLE
No dependencies defined in pom.xml may cause compatibility issue

### ISSUE THREAD

**Issue by chzhong** [OpenFeign/feign-form#59]
Consider the following pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.19.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
        <dependencies>
       <!- ... -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
		</dependency>
                <dependency>
                         <groupId>io.github.openfeign.form</groupId>
                         <artifactId>feign-form-spring</artifactId>
                         <version>3.5.0</version>
                  </dependency>
        <!- ... -->
	</dependencies>
</project>
```

Spring 1.5.x uses feign-core 9.5.0, however, feign-form-spring 3.5.0 depends on a  class `feign.Request.Body` which introduced in feign-core 10.2.0.

Feign 9.x users upgrade feign-form to 3.5.0 would result in a NoClassDefFoudError without compilation error:
```
Caused by: java.lang.NoClassDefFoundError: feign/Request$Body
	at feign.form.MultipartFormContentProcessor.process(MultipartFormContentProcessor.java:99) ~[feign-form-3.5.0.jar:?]
	at feign.form.FormEncoder.encode(FormEncoder.java:105) ~[feign-form-3.5.0.jar:?]
	at feign.form.spring.SpringFormEncoder.encode(SpringFormEncoder.java:70) ~[feign-form-spring-3.5.0.jar:?]
```

Please consider adding dependencies to feign-form's pom.xml, so that maven would resolve dependency issue.

**Comment by xxlabaza** [comment]
thanks for help @chzhong for your issue, I have updated the readme with a [Requirements](https://github.com/OpenFeign/feign-form#requirements) section

**Comment by mhaisma** [comment]
The requirements section is not correct. It currently states the following:

> starting from feign-form's version 3.5.0, the module works with OpenFeign 10.* versions.

I just encountered the same NoClassDefFoundError despite using a 10.* version (10.0.1) of Feign. After double-checking the requirements section to see if the version we had been using for the project would work. 

The version needed is 10.2.0 or greater, not 10.*.

**Comment by xxlabaza** [comment]
@mhaisma thanks for your issue report, I have fixed the README.md
