### ISSUE TITLE
Publish under OpenFeign group on Bintray

### ISSUE THREAD

**Issue by xxlabaza** [OpenFeign/feign-form#6]
Subj

**Comment by adriancole** [comment]
probably the coordinates should be "io.github.openfeign.form:feign-form" just to make sure deployments don't clash. wdyt y'all? cc @spencergibb

**Comment by adriancole** [comment]
once we decide, we should link this to jcenter accordingly https://bintray.com/openfeign/maven/feign-form

**Comment by spencergibb** [comment]
I think `io.github.openfeign.form:feign-form` is fine.

**Comment by adriancole** [comment]
just requested this to be linked to bintray with io.github.openfeign.form group id

https://bintray.com/openfeign/maven/feign-form

**Comment by adriancole** [comment]
next step: make the root pom and travis file look like feign's so that publishing things will work.

@xxlabaza wanna give that a try?

**Comment by xxlabaza** [comment]
I have edited pom.xml and published 2.0.2 version to bintray and synced it manually (via your centralsync-maven-plugin). Do you have any kind of instructions how to setup travis file?

**Comment by adriancole** [comment]
this should help https://github.com/OpenFeign/feign/pull/460

**Comment by xxlabaza** [comment]
Yeap, thanks a lot, I did it)

**Comment by adriancole** [comment]
whoot! thanks for accepting the challenge.. and.. now you are
self-sufficient!
