### ISSUE TITLE
UrlFormEncoder does not handle Map<String,Collection> correctly

### ISSUE THREAD

**Issue by wh81752** [OpenFeign/feign-form#60]
Hello,

if I understand https://www.w3.org/TR/html4/interact/forms.html correctly, then control names may appear more than once within a form.

Therefore 

 ```
Map<String,List<String>> mymap = ..;
 mymap.put("name", Arrays.asList("bob", "alice"));
 encode(mymap);
```

should encode as

`
name=bob&name=alice
`

Thus your form encoder must assume Map<String,Collection<Object>> as fundamental data structure instead of Map<String, Object>.

**Comment by xxlabaza** [comment]
fixed

**Comment by wh81752** [comment]
Hello there,

not 100% convinced that your code handle all scenarios. How about this four distinct cases:

1. Map<String, Iterable>   ;; this appears to handle all collections but Map
2. Map<String, Map>        ;; special handling
3. Map<String, Object>     ;; neither collection nor Map
4. PoJo                               ;; iterate over properties

Case 4 is interesting as well:

class MyPojo {
    List name = Arrays.asList("bob", "alice");
    int age = 42;
 }

This should encode as:
 
  name=bob&name=alice&age=42

I believe it happens automatically cause, if I understand the code proper, you map a PoJo into a Map and you serialize then in a second step the map.
