### ISSUE TITLE
Doku: Requirement section missing

### ISSUE THREAD

**Issue by wh81752** [OpenFeign/feign-form#61]
Hello,

please add a section Requirement in your documentation. Please state there which openfeign version you depend on.

For example, feign-form-3.5 will not work with openfeign-9.x (ClassNotFound Exception on feign/Request.$Body), thus at least openfeign-10.x is required.

**Comment by xxlabaza** [comment]
thanks for help @wh81752, I have updated the readme with a [Requirements](https://github.com/OpenFeign/feign-form#requirements) section
