### ISSUE TITLE
POJO properties to form properties

### ISSUE THREAD

**Issue by marembo2008** [OpenFeign/feign-form#65]
Consider the following pojo:
```
class Pojo {
  String firstName;
  String idNumber;
}
```

And we would like to map it to `x-www-form-urlencoded` as:
```
f_name={firstName}
id_no={idNumber}
```

We propose to use a property name to form value key mapper as:

```
class Pojo {
  @FormProperty("f_name")
  String firstName;

  @FormProperty("id_no")
  String idNumber;
}
```

**Comment by marembo2008** [comment]
@xxlabaza please comment if this issue is worth an improvement

**Comment by xxlabaza** [comment]
@marembo2008 I will take a look at this in the end of the week. Sorry, too much work
