### ISSUE TITLE
Modify part name when send existing object of MultipartFile.

### ISSUE THREAD

**Issue by JokerSun** [OpenFeign/feign-form#70]
First explain my problem.
 
 I have 2 server A and B, a file such as 'file1' is uploaded to A by MultipartFile , then i will process the file but no reconstruct the object and send it to B server by fein client and use the different part name such as 'file2'.

  And then  i try specify the part name in annotation, like this `@RequestPart("file2")`, but it doesn't work.

  After i read the code of spring-feign-form-encoder, i find that it use the return value of method `MultipartFile.getName()` as part name, but MultipartFile can not modify this field.

  So I am lost in confusion, is there any solution?

**Comment by JokerSun** [comment]
Well, the project looks not very active.

**Comment by GongchuangSu** [comment]
I've got the same problem too, this is a general problem.But no one seems to be here to fix it.

**Comment by GongchuangSu** [comment]
I‘ve created a [issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/358) in spring cloud openfeign, may be more active...
